name: xr-dash
channels:
  - pyviz
  - defaults
dependencies:
  - bokeh ==1.2.0
  - datashader ==0.7.0
  - matplotlib
  - notebook
  - numpy ==1.16.4
  - pandas ==0.24.0
  - python ==3.6.*
  - xlrd
  - pyviz
  - hvplot